export const TODOS_UPDATE_TASK_LIST = 'TODOS_UPDATE_TASK_LIST';

export const TODOS_DELETE_TASK_LIST = 'TODOS_DELETE_TASK';

export const TODOS_MODIFY_TASK_LIST = 'TODOS_UPDATE_TASK';

export const TODOS_CHOSEN_TASK_LIST = 'TODOS_CHOSEN_TASK';